### ISSUE TITLE
RtHz isn't enabled

### ISSUE THREAD

**Issue by QuantAsylum** [QuantAsylum/QA40x#17]
The setting for RtHz display is greyed-out

**Comment by codegame** [comment]
You can try the following modification method:
1. New Settings -> Save Settings
2. Modify the configuration file you just saved and find the following information:
  <UiSettings><Presets><PresetList>
<GraphPreset>
    <YAxisUnits>DbvRtHz</YAxisUnits> //<--Edit it [DbvRtHz].
</GraphPreset>
3. Save the configuration file and open it again, you will find that dBvRtHz has been displayed.

![QA1](https://user-images.githubusercontent.com/2607996/174250092-d197c2f7-ac4a-48df-8ecc-c563b774d26b.png)
![QA3](https://user-images.githubusercontent.com/2607996/174250103-7f36f7e8-e0cc-47a9-a91b-a634a6a28fbe.png)

The above modification is only for unit display, and there is no guarantee that there are other calculation processes that are not involved. Good luck!

**Comment by QuantAsylum** [comment]
Fixed in 1.154
