### ISSUE TITLE
Vertical Y Units for Noise Measurements

### ISSUE THREAD

**Issue by codegame** [QuantAsylum/QA40x#22]
Y-axis units are currently too scarce. For the measurement of noise parameters, although there is currently dBV, it requires tedious conversion calculations, so it is necessary to use the commonly used noise measurement units (uV)rtHz and (nV)rtHz. A custom conversion function or plugin, this feature is looking forward to seeing it in the next new version, thanks.

**Comment by QuantAsylum** [comment]
Yes, agree and we will study. I have the same issues with the hand conversions. It's tedious.

**Comment by QuantAsylum** [comment]
RtHz is enabled in 1.154 (see dBV context menu) but it will take more time to get non-log Y axis

**Comment by NoiseFree** [comment]
Suggestion: loglog plot with linear x and y values is very readable

![image](https://user-images.githubusercontent.com/132371610/235725054-81231220-9286-4493-9873-d5575c63f428.png)

**Comment by QuantAsylum** [comment]
This is in 1.175. The right-side of the main plot will show volts/rthz and the left side will show dB (as today).

https://github.com/QuantAsylum/QA40x/releases/tag/1.175

**Comment by NoiseFree** [comment]
Thanks for the improvement! 

A toggle grid setting would be the icing on the cake.
