### ISSUE TITLE
Noise Spectral Density Measurement (Rt Hz) depends on window function

### ISSUE THREAD

**Issue by NoiseFree** [QuantAsylum/QA40x#31]
Hi, 

I encountered a bug with the noise spectral density measurement. I wanted to validate the measurement with a known DUT. So I prepared the following OpAmp circuit (Non-Inverting Amp with OPA828, metal film resistors, input shorted with 50 Ohms):

![image](https://user-images.githubusercontent.com/132371610/235713536-45d2554e-73b3-4e6c-aa75-d07173a60026.png)

Simulation says, it has a noise spectral density of around 4.2 nV/rtHz (broadband noise between 1kHz to 10kHz):

![image](https://user-images.githubusercontent.com/132371610/235713885-f0597d52-e55a-406a-9f49-3ac413c3de6f.png)

The measurement with the QA403 depends strongly on the window used:

![image](https://user-images.githubusercontent.com/132371610/235716060-3c3f650d-1c49-4337-8c1d-03ec84499c0b.png)

From a user point of view the spectral density shouldn't depend on either the FFT size nor the window function used. So far, Rt Hz mode compensates for FFT size only, like it is discribed in the GUI. But I think the scaling isn't done correctly yet. A correction factor for window functions should also be involved, like it is mentioned here: 

https://www.ap.com/technical-library/fft-scaling-for-noise/   

Looking forward to your answer.
Regards

**Comment by QuantAsylum** [comment]
Hi @NoiseFree, can you verify if on your plot that the RMS is reported correctly regardless of window setting? Yes, I see the shift in trace as you do

**Comment by NoiseFree** [comment]
RMS value stays the same regardless of window setting

**Comment by QuantAsylum** [comment]
This has been fixed for release 1.174 out later today. In this release, you can verify for RECT or other windows (HANN, FlatTop, etc) the displayed Y value of measured noise remains the same when RTHZ is enabled via the DBV context menu. Please confirm at your convenience, and thanks very much for reporting this.

**Comment by QuantAsylum** [comment]
Link is here: https://github.com/QuantAsylum/QA40x/releases/tag/1.175. 

Please re-open if you see an issue.
