### ISSUE TITLE
Noise density graph seems to be slightly offset

### ISSUE THREAD

**Issue by NoiseFree** [QuantAsylum/QA40x#32]
Thanks for the fix! I can confirm that the measurement is not window dependent anymore.

But there is still an issue with the display. It seems that it's off by about 1 dB. 

To profe that I measured the spectral density of an 1MOhm resistor at room temperature. The circuit is the same non-inverting amp as shown above with the 50 Ohms removed.

![image](https://github.com/QuantAsylum/QA40x/assets/132371610/3c64fe1d-c7ee-4ea7-82c0-732b35a44f10)

_Originally posted by @NoiseFree in https://github.com/QuantAsylum/QA40x/issues/31#issuecomment-1544174770_

**Comment by QuantAsylum** [comment]
Hi @NoiseFree, thanks for the data. On my end, the noise test circuit looks as follows:

![image](https://github.com/QuantAsylum/QA40x/assets/27789827/76a65421-f7f6-4f30-b755-65d52f7dc52a)

The OPA377 is 7.5nV/rthz (typ @ 1k), which is -162.5 dBV. So, the circuit above should be dominated by the R noise, which in this case is 500K equivalent, which is should yield -140.92 dBV at 68F (my current temperature). 

I measure the following, which looks pretty much on to me (this is 900 to 1100 Hz). What do you think of the math above?

![image](https://github.com/QuantAsylum/QA40x/assets/27789827/2831ba7e-be36-46b8-a130-237a39b819ce)

Is there a chance you gain setting resistors might have a contribution? If they are 1% or better, probably not. If you set the opamp gain to unity, does the error get better or worse?
