### ISSUE TITLE
Extend distortion measurements below ~23 Hz

### ISSUE THREAD

**Issue by QuantAsylum** [QuantAsylum/QA40x#8]
https://forum.quantasylum.com/t/100-distortion-at-20-3hz-in-loopback/485

**Comment by blurpy** [comment]
Not sure if this is related, but in addition to 100% THD at 20Hz, it returns infinity above 7kHz when doing a 20-20000Hz sweep.

![Screenshot 2021-09-30 at 20-11-39 QA40x Web - Frequency Sweep](https://user-images.githubusercontent.com/186016/135509625-9d37fd32-6f46-4c8a-bafe-730d6422eaf7.png)

It goes to 10kHz on the QA401 with the same settings. Is this a bug?

**Comment by blurpy** [comment]
Oh, the QA401 goes to 9kHz actually, not 10kHz:
![Screenshot 2021-10-02 at 12-14-06 QA401 Web - Frequency Sweep](https://user-images.githubusercontent.com/186016/135712002-d7d6144a-8e96-427c-a398-b86a91f7ef28.png)
